setup: 
  - name: update apt-get
    cmd: sudo apt-get update
  - name: update apt
    cmd: sudo apt update
  - name: install git
    cmd: sudo apt-get install -y git-all
  - name: install java 11
    cmd: sudo apt install -y openjdk-11-jdk 
  - name: install mysql 8
    cmd: sudo apt-get install -y mysql-server
  - name: install maven
    cmd: sudo apt-get install -y maven
  - name: install git
    cmd: sudo apt-get install -y git
  - name: create mysql init file
    cmd: |
      "echo 'ALTER USER '\''root'\''@'\''localhost'\'' IDENTIFIED BY '\''{MYSWL_PSSW}'\'';' >> mysql-pwd"
  - name: studown mysql
    cmd: sudo service mysql stop
  - name: initialize mysql password
    cmd: |
      sudo mysqld --init-file=~/mysql-pwd
  - name: restart mysql
    cmd: sudo service mysql start
  - name: remove password file
    cmd: |
      "sudo rm ~/mysql-pwd"

jobs:
  - name: itrust-build
    steps:
      - name: Copy application.yml.template
        cmd: git clone https://github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git
      - name: Rename to application.yml
        cmd: cp iTrust2-v10/blob/main/iTrust2/src/main/resources/application.yml.template iTrust2-v10/blob/main/iTrust2/src/main/resources/application.yml
      - name: Add SQL password
        cmd: sed 's/password:/password:\s{MYSQL_PSSW}/' iTrust2-v10/blob/main/iTrust2/src/main/resources/application.yml
      - name: Run iTrust2
        cmd: cd iTrust2-v10 && mvn --batch-mode --update-snapshots clean test
