setup: 
  - name: synchronize system time
    cmd: sudo systemctl restart systemd-timesyncd.service
  - name: update apt
    cmd: sudo apt update
  - name: remove flash-kernel
    cmd: "'sudo apt remove -y flash-kernel && sudo apt -y autoremove'"
  - name: install java 11
    cmd:  sudo apt install -y openjdk-11-jre-headless -qq
  - name: install mysql 8
    cmd: sudo apt install -y mysql-server -qq
  - name: install maven
    cmd: sudo apt install -y maven -qq
  - name: install git
    cmd: sudo apt install -y git -qq
  - name: install node
    cmd: sudo apt install -y nodejs npm -qq
  - name: install uuid for pm2
    cmd: sudo npm install uuid@latest -g
  - name: instal pm2
    cmd: sudo npm install pm2 -g
  - name: install browser for puppteer
    cmd: sudo apt install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils  -qq
  - name: stop apt-daily timer to look for updates
    cmd: sudo systemctl stop apt-daily.timer
  - name: reset user in mysql
    cmd: |
      "sudo mysql -e \"DROP USER IF EXISTS 'admin'@'localhost' ;\""
  - name: create a new user in mysql
    cmd: |
      "sudo mysql -e \"CREATE USER 'admin'@'localhost' IDENTIFIED WITH mysql_native_password BY '{MYSQL_PSSW}';\""
  - name: grant privileges for the new user
    cmd: |
      "sudo mysql -e \"GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';\""

jobs:
  - name: itrust-build
    steps:
      - name: clone latest version of iTrust2
        cmd: git clone https://{GIT_USER}:{TOKEN}@github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git
      - name: copy  application.yml.template to application.yml
        cmd: cp iTrust2-v10/iTrust2/src/main/resources/application.yml.template iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: update user in application.yml
        cmd: sed -i 's/username:\ [a-z]*/username:\ admin/' iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: update password in application.yml
        cmd: sed -i 's/password:/password:\ {MYSQL_PSSW}/' iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: Run iTrust2
        cmd: "'cd iTrust2-v10/iTrust2 && mvn --batch-mode --update-snapshots clean test'"
    cleanup:
      - name: remove iTrust2-v10 repo
        cmd: rm -rf iTrust2-v10
  - name: mutation-coverage
    steps:
      - name: remove all screenshot
        cmd: rm -rf {VOLUME}/screenshots
      - name: make directory for screenshots
        cmd: mkdir {VOLUME}/screenshots
      - name: clone the microservice
        cmd: git clone https://github.com/chrisparnin/checkbox.io-micro-preview.git
      - name: move Testharness to ~/
        cmd: cp -r {VOLUME}/ASTRewrite ASTRewrite/
      - name: install node dependencies for microservice
        cmd: "'cd ~/checkbox.io-micro-preview && npm install'"
      - name: install node dependencies for Testharness
        cmd: "'cd ~/ASTRewrite && npm install'"
      - name: start mutation test
        cmd: "'node ASTRewrite/index.js testharness ~/checkbox.io-micro-preview/marqdown.js'"
    cleanup:
      - name: remove all web from pm2
        cmd: pm2 kill
      - name: remove ASTRewrite repo
        cmd: rm -rf ASTRewrite
      - name: remove microservice repo
        cmd: rm -rf checkbox.io-micro-preview
