setup: 
  - name: update apt-get
    cmd: sudo apt-get update
  - name: install java 11
    cmd: sudo apt-get install -y openjdk-11-jdk 
  - name: install mysql 8
    cmd: sudo apt-get install -y mysql-server
  - name: install maven
    cmd: sudo apt-get install -y maven
  # - name: setting muysql password
  #   cmd: |
  #       sudo mysql 
  #       ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{mysql_pssw}'
  #       exit

jobs:
  - name: build-itrust
    steps:
      - name: Copy application.yml.template
        run: wget https://github.ncsu.edu/engr-csc326-staff/iTrust2-v10/blob/main/iTrust2/src/main/resources/application.yml.template
      - name: Rename to application.yml
        run: cp application.yml.template application.yml
      - name: Run iTrust2
        run: cd iTrust2 && mvn --batch-mode --update-snapshots clean test