setup: 
  - name: update apt-get
    cmd: sudo apt-get update
  - name: install java 11
    cmd: sudo apt-get install -y openjdk-11-jdk 
  - name: install mysql 8
    cmd: sudo apt-get install -y mysql-server
  - name: install maven
    cmd: sudo apt-get install -y maven
  - name: create mysql init file
    cmd: |
      "echo 'ALTER USER '\''root'\''@'\''localhost'\'' IDENTIFIED BY '\''{mysql_pssw}'\'';' >> mysql-pwd"
  - name: studown mysql
    cmd: sudo service mysql stop
  - name: initialize mysql password
    cmd: sudo mysqld --init-file=~/mysql-pwd
  - name: restart mysql
    cmd: sudo service mysql start
  - name: remove password file
    cmd: |
      "sudo rm ~/mysql-pwd"

jobs:
  - name: build-itrust
    steps: 
      - name: ls
        command: ls
      - name: Install nodejs
        apt: pkg='nodejs' state='present'