setup: 
  - name: synchronize system time
    cmd: sudo systemctl restart systemd-timesyncd.service
  - name: update apt
    cmd: sudo apt update
  - name: remove flash-kernel
    cmd: "'sudo apt remove -y flash-kernel && sudo apt -y autoremove'"
  - name: install java 11
    cmd:  sudo apt install -y openjdk-11-jre-headless -qq
  - name: install mysql 8
    cmd: sudo apt install -y mysql-server -qq
  - name: install maven
    cmd: sudo apt install -y maven -qq
  - name: install git
    cmd: sudo apt install -y git -qq
  - name: stop apt-daily timer to look for updates
    cmd: sudo systemctl stop apt-daily.timer
  - name: set new password for root user in mysql
    cmd: |
      "mysqladmin -uroot -p{MYSQL_PSSW} ping | grep -c 'mysqld is alive' || 
      sudo mysql -e \"ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{MYSQL_PSSW}';\""

jobs:
  - name: itrust-build
    steps:
      - name: clone latest version of iTrust2
        cmd: "'rm -rf iTrust2-v10 && git clone https://{GIT_USER}:{TOKEN}@github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git'"
      - name: copy  application.yml.template to application.yml
        cmd: cp iTrust2-v10/iTrust2/src/main/resources/application.yml.template iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: update password in application.yml
        cmd: sed -i 's/password:/password:\ {MYSQL_PSSW}/' iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: Run iTrust2
        cmd: "'cd iTrust2-v10/iTrust2 && mvn --batch-mode --update-snapshots clean test'"
    cleanup:
      - name: remove iTrust2-v10 repo
        cmd: rm -rf iTrust2-v10
